baseURL = "/"
languageCode = "ja-jp"
title = "技術科部"
themesDir = "./themes"
theme = "hugo-serif-theme"

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  title="Home | 技術科部"
  google_analytics_id = "UA-111958560-20"
  google_tag_manager_id = ""

  [params.logo]
    mobile = "images/logo-mobile.png"
    standard  = "images/logo.png"
    alt = "Technical Club Official Site"

  [params.homepage_meta_tags]
    meta_description = "Technical Club Official Site"
    meta_og_title = "技術科部"
    meta_og_type = "website"
    meta_og_url = "https://www.tech-hugo.cf"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
    meta_og_description = "Technical Club Official Site"
    meta_twitter_card = "summary"
    meta_twitter_site = "@tech_chiba"
    meta_twitter_creator = "@tech_chiba"

[menu]
  # Main Menu
  [[menu.main]]
    name = "企画"
    url = "/product/"
      weight = 1

  [[menu.main]]
      name = "チーム"
      url = "/team/"
      weight = 2

  # Footer Menu
  [[menu.footer]]
    name = "ホーム"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "お問い合わせ"
    url = "/contact/"
      weight = 2

  [[menu.footer]]
    name = "管理画面"
    url = "/admin/"
      weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
